builders:
  bin_builder:
    import: 'tool/bin_builder.dart'
    builder_factories: ['binBuilder']
    build_extensions: { '.bin.dart': ['.dart'] }
    build_to: source

targets:
  $default:
    builders:
      btool|bin_builder:
        generate_for:
          - bin/btool.bin.dart
