name: btool
description: Generic build helper tools for Flutter/Dart such as manipulating version, package name or application ID
version: 0.1.5
homepage: 'https://github.com/chenasraf/btool'

executables:
  btool: btool

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  file: ^7.0.0
  path: ^1.8.3

dev_dependencies:
  build:
  build_runner:
  flutter_lints:
  test:

script_runner:
  scripts:
    - activate-local: 'dart pub global activate --source path ./'
    - activate-global: 'dart pub global activate btool'
    - auto-fix: dart fix --apply
    - publish: dart format .; dart pub publish; format
    - watch: dart run build_runner watch --delete-conflicting-outputs
    - format: dart format --line-length 120 .
