name: btool
description: Generic build helper tools for flutter
version: 0.1.1
homepage: 'https://github.com/chenasraf/btool'

executables:
  btool: btool

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.1
  colorize: ^3.0.0
  file: ^6.1.4
  path: ^1.8.2

dev_dependencies:
  build:
  build_runner:
  flutter_lints:
  test:

script_runner:
  scripts:
    - activate-local: 'dart pub global activate --source path ./'
    - activate-global: 'dart pub global activate btool'
    - auto-fix: dart fix --apply
    - publish: dart pub publish -f
    - watch: dart run build_runner watch --delete-conflicting-outputs
