name: btool
description: Generic build helper tools for flutter
version: 0.0.1
homepage: 'https://github.com/chenastag/btool'

executables:
  btool: main.bin

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  args: ^2.3.1
  colorize: ^3.0.0
  file: ^6.1.4
  path: ^1.8.2
  test: ^1.22.0

dev_dependencies:
  build:
  build_runner:
  flutter_lints:

script_runner:
  scripts:
    - activate-local: 'dart pub global activate --source path ./'
    - activate-global: 'dart pub global activate btool'
    - auto-fix: dart fix --apply
